query queryTopology {
    topology: getServicesTopology(duration: {{ duration.to_gql() }}, serviceIds: {{ service_ids }}) {
        nodes {
            id name type
        }
        calls {
            source target
        }
    }
}